filebeat.modules:
  - module: http-audit
    app:
      enabled: true
      var.paths: ["/data/logs/suricata/app_audit.json"]


output.logstash:
  hosts: ["192.168.199.97:5020"]
  loadbalance: true
  worker: 4
  compression_level: 3
  bulk_max_size: 4096
